In [1]:
import numpy as np

In [4]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
ar # age aage me [ ho to 1 dimensional  hai # 1 dimensional ko sife ak line chaye use x axis me likhadete hai

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]]) # # age aage  me [[ ho to 2 dimensional  hai # 2 dimensional y,x axis me data lekha jata 
#✅ Numpy array = (row, column) = (y, x)

#Yaani:

#Row = y direction (vertical)

#Column = x direction (horizontal)

array([[1, 2],
       [3, 4]])

In [7]:
arr = np.asarray(l)

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [10]:
a = [2,5,6]

In [11]:
arrr = np.asanyarray(a)

In [12]:
arrr

array([2, 5, 6])

In [13]:
type(arrr)

numpy.ndarray

In [5]:
l

[1, 2, 3, 4]

In [15]:
b = np.matrix(l) # matrix by default 2 dimensional h  hota hai (fix hai✅ )

In [16]:
b

matrix([[1, 2, 3, 4]])

In [17]:
np.asanyarray(b) # conveart nahi karega koki matrix(sub class of array) kya array ka hi part hai 

matrix([[1, 2, 3, 4]])

In [6]:
a = np.array(l)

In [7]:

a

array([1, 2, 3, 4])

In [20]:
c = a

In [21]:
c

array([1, 2, 3, 4])

In [22]:
a

array([1, 2, 3, 4])

In [23]:
c[0] = 200

In [24]:
c

array([200,   2,   3,   4])

In [25]:
a

array([200,   2,   3,   4])

In [26]:
d = np.copy(a) # copy ho jata dusar jagah rakha jata hai a != d 

In [27]:
d

array([200,   2,   3,   4])

In [28]:
a

array([200,   2,   3,   4])

In [29]:
a[1] = 400

In [30]:
a

array([200, 400,   3,   4])

In [31]:
d

array([200,   2,   3,   4])

In [32]:
np.fromfunction(lambda i,j : i==j ,(3,3)) #(3,3) dimensional ka array  hai ye by defaulit (0) se suro hota ahi , (3,3)  index(0,1,2)  hai 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable = ( i*i for i in range(5))

In [35]:
iterable #<generator object  ko bhi  hi iterable varible kahte hai

<generator object <genexpr> at 0x00000120757BCA00>

In [36]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
np.fromstring('234 235',sep= ' ') #sep(separating ) kya alg kaene ka parameter diya jata hai 

array([234., 235.])

In [38]:
np.fromstring('234,235',sep= ',') # sep dena hota hai kyuki gandu ye string hai

array([234., 235.])

In [39]:
#numpy - data types

In [40]:
l = [2,3,4,5,6]

In [41]:
ar=  np.array(l) 

In [42]:
ar

array([2, 3, 4, 5, 6])

In [43]:
ar.ndim #dimensional bata hai 

1

In [44]:
ar2 = np.array([[1,2,3],[3,2,1]])

In [45]:
ar2

array([[1, 2, 3],
       [3, 2, 1]])

In [46]:
ar2.ndim

2

In [47]:
ar.size # number of element 

5

In [48]:
ar2.size

6

In [49]:
ar.shape #1D array ka koi row–column concept (structure) hota hi nahi hai .

(5,)

In [50]:
ar2.shape #shap bata hai kitna row and collumas hai (2,3) first row(2) and second collums(3) hamesa hota hai 

(2, 3)

In [51]:
ar.dtype

dtype('int64')

In [52]:
ar2.dtype

dtype('int64')

In [53]:
ar22 = np.array([(1.4,25,45), (21,45,66)]) #2 dimensional bana [] ander valu hona chaye

In [54]:
ar22

array([[ 1.4, 25. , 45. ],
       [21. , 45. , 66. ]])

In [55]:
ar22.dtype # ak float sabko folat bana deta hai 

dtype('float64')

In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [57]:
list(range(1,5,2)) # 2 jump 

[1, 3]

In [58]:
list(range(0.1,5)) # range float point nahi  lega

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(2.3,6.2)

In [59]:
np.arange(2.3,6.2,0.5) # 0.5 jump hai 

array([2.3, 2.8, 3.3, 3.8, 4.3, 4.8, 5.3, 5.8])

In [60]:
list(np.arange(2.3,6.2,0.5))# 0.5 jump hai 

[np.float64(2.3),
 np.float64(2.8),
 np.float64(3.3),
 np.float64(3.8),
 np.float64(4.3),
 np.float64(4.8),
 np.float64(5.3),
 np.float64(5.8)]

In [61]:
a =np.linspace(1,5,10)
#Start value: 1
#End value: 5
#Total numbers: 10 data dega (equal gap ke saath)
#Yaani 1 se 5 ke beech 10 equally spaced values banenge.

In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [63]:
np.zeros((3,4)) # first row(3) and second collums(4) hamesa hota hai 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.zeros((3,4,2)) # 3D dimensional kha te kese (4,2) 4 row 2 collums ,(3) array(maryix)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [65]:
np.zeros((3,4,2)).ndim

3

In [66]:
np.zeros((3,4,2,3)) # 2,3 = 2 row 3 collums 4 array 3 time hai  app ise graphcal me represent nahi kar sate ho 

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [67]:
np.ones(4)

array([1., 1., 1., 1.])

In [68]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
on = np.ones((2,3,2))

In [70]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [71]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [72]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [73]:
on - 1

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [74]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

np.empty((3,6)) ➡ Numpy array ka size bana diya (shape decide kar di)

Par andar koi value fill nahi ki

Jo memory me pehle se kuch random data pada hota hai, woh hi array me dikh jata hai

In [75]:
np.eye(4) #eye matrix me Diagonal me 1 Baaki sab jagah 0
#Diagonal = Seedhi line jo matrix ke upar-left(↘) se neeche-right(↖) jaati hai.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
np.linspace(2,4,20) # 2 aur 4 beacb 20 data genratet kar rahai

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [77]:
np.logspace(2,5,10, base=2) # same linspace ka yah sif log nikal ki de raha  

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [78]:
ar3 = np.random.randn(3,4) # random data ko produst(dega) karta hai #mean = 0 ,std  = 1 data hoga genarater karta hai

In [79]:
ar3

array([[-0.07235807, -0.20330659,  0.14643618, -1.5522454 ],
       [-0.32341666, -1.41576322,  0.81560368,  1.11452503],
       [-0.79518766, -0.6925015 , -0.78021663, -1.99977203]])

In [80]:
import pandas as pd

In [81]:
pd.DataFrame(ar3)

0         1         2         3
0 -0.072358 -0.203307  0.146436 -1.552245
1 -0.323417 -1.415763  0.815604  1.114525
2 -0.795188 -0.692502 -0.780217 -1.999772

In [82]:
np.random.rand(3,4)  # random data ko produt(bana) karta hai

array([[0.80326718, 0.58880003, 0.9017341 , 0.1782606 ],
       [0.53086785, 0.20362155, 0.97367693, 0.84411551],
       [0.49243602, 0.04769864, 0.88435197, 0.61142835]])

In [83]:
 are = np.random.randint(1,5,(300,400)) # int hi  deta hai our range bhi de sakte ho ki yaha se our eske bich valau le  ex - 1,5

In [84]:
pd.DataFrame(are).to_csv('test.csv',index= False)

In [ ]:
#numpy - array manipulation

In [85]:
arrr8 =  np.random.rand(3,4)

In [86]:
arrr8

array([[0.37293725, 0.4680695 , 0.9359458 , 0.05492868],
       [0.10124633, 0.7973179 , 0.12424006, 0.16214183],
       [0.99232217, 0.97145537, 0.68111728, 0.40317848]])

In [87]:
arrr8.reshape(6,3) # resahpe tab karega arr(12 data row + collums le kar milake) me jita data hai dono se mulitple karne se otna data aana chayr reshape karne par 

ValueError: cannot reshape array of size 12 into shape (6,3)

In [88]:
arrr8.reshape(6,2) # 6 * 2 = 12

array([[0.37293725, 0.4680695 ],
       [0.9359458 , 0.05492868],
       [0.10124633, 0.7973179 ],
       [0.12424006, 0.16214183],
       [0.99232217, 0.97145537],
       [0.68111728, 0.40317848]])

In [89]:
arrr8.reshape(6,-15656222) # by defaulit he samjhta hai ki (-) jo  phele value kese multiple karne se 12 atega o apne ap  value le leta hai jis * 12 yega 

array([[0.37293725, 0.4680695 ],
       [0.9359458 , 0.05492868],
       [0.10124633, 0.7973179 ],
       [0.12424006, 0.16214183],
       [0.99232217, 0.97145537],
       [0.68111728, 0.40317848]])

In [90]:
arrr8.reshape(5,-15656222)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [91]:
arrr8.reshape(4,3) # 6 * 2 = 12

array([[0.37293725, 0.4680695 , 0.9359458 ],
       [0.05492868, 0.10124633, 0.7973179 ],
       [0.12424006, 0.16214183, 0.99232217],
       [0.97145537, 0.68111728, 0.40317848]])

In [93]:
arrr8.reshape(4,-233)  # by defaulit he samjhta hai ki (-) valu hai  jo  phele value se automatic (*MULITPLE) karna shura karta hai ki  kese multiple karne se 12 atega o apne ap  value le leta hai jis * 12 yega 

array([[0.37293725, 0.4680695 , 0.9359458 ],
       [0.05492868, 0.10124633, 0.7973179 ],
       [0.12424006, 0.16214183, 0.99232217],
       [0.97145537, 0.68111728, 0.40317848]])

In [94]:
arrr8

array([[0.37293725, 0.4680695 , 0.9359458 , 0.05492868],
       [0.10124633, 0.7973179 , 0.12424006, 0.16214183],
       [0.99232217, 0.97145537, 0.68111728, 0.40317848]])

In [96]:
arrr8[1][2]

np.float64(0.12424005881169775)

In [104]:
arrr8[1:3,3] # uper - 1 ye  par 1:3 kyahai row ,3 collums  index hai 

array([0.16214183, 0.40317848])

In [106]:
arr = np.random.randint(1,100 ,(5,5))

In [107]:
arr

array([[ 1, 71, 50,  2, 81],
       [82, 86, 66, 58,  6],
       [31, 20, 12, 98, 65],
       [39, 92, 88, 81,  8],
       [90, 82, 28, 48,  2]], dtype=int32)

In [108]:
arr > 50

array([[False,  True, False, False,  True],
       [ True,  True,  True,  True, False],
       [False, False, False,  True,  True],
       [False,  True,  True,  True, False],
       [ True,  True, False, False, False]])

In [109]:
arr[arr > 50]

array([71, 81, 82, 86, 66, 58, 98, 65, 92, 88, 81, 90, 82], dtype=int32)

In [113]:
arr

array([[ 1, 71, 50,  2, 81],
       [82, 86, 66, 58,  6],
       [31, 20, 12, 98, 65],
       [39, 92, 88, 81,  8],
       [90, 82, 28, 48,  2]], dtype=int32)

In [116]:
arr[2:4,2:4] #dono me hoga  uper - 1

array([[12, 98],
       [88, 81]], dtype=int32)

In [117]:
arr[2:4,[2,3]]

array([[12, 98],
       [88, 81]], dtype=int32)

In [119]:
arr[0,0] = 5000

In [120]:
arr

array([[5000,   71,   50,    2,   81],
       [  82,   86,   66,   58,    6],
       [  31,   20,   12,   98,   65],
       [  39,   92,   88,   81,    8],
       [  90,   82,   28,   48,    2]], dtype=int32)

In [122]:
arr1 = np.random.randint(1,3,(3,3))

In [123]:
arr2 = np.random.randint(1,3,(3,3))

In [124]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [1, 2, 2]], dtype=int32)

In [125]:
arr2

array([[1, 2, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [126]:
arr1 + arr2

array([[2, 4, 2],
       [4, 3, 3],
       [2, 4, 3]], dtype=int32)

In [127]:
arr1 - arr2

array([[ 0,  0,  0],
       [ 0,  1, -1],
       [ 0,  0,  1]], dtype=int32)

In [128]:
arr1 * arr2 # normal multiption hai index se ho raha hai 

array([[1, 4, 1],
       [4, 2, 2],
       [1, 4, 2]], dtype=int32)

In [129]:
arr1 / arr2

array([[1. , 1. , 1. ],
       [1. , 2. , 0.5],
       [1. , 1. , 2. ]])

In [130]:
arr1@arr2 # martix mulitption hai 

array([[6, 6, 6],
       [7, 8, 7],
       [7, 8, 7]], dtype=int32)

In [134]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [1, 2, 2]], dtype=int32)

In [132]:
arr1/0

C:\Users\frontech\AppData\Local\Temp\ipykernel_10128\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [133]:
arr1 + 100

array([[101, 102, 101],
       [102, 102, 101],
       [101, 102, 102]], dtype=int32)

In [135]:
arr1**2

array([[1, 4, 1],
       [4, 4, 1],
       [1, 4, 4]], dtype=int32)

In [ ]:
#numpy - broadcasting

In [137]:
arr = np.zeros((4,4))

In [138]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [139]:
row = np.array([1,2,3,4])

In [140]:
row

array([1, 2, 3, 4])

In [141]:
arr + row # row by row add ho raha 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [142]:
row.T # 1D kabhi bhi nahi gomega 

array([1, 2, 3, 4])

In [144]:
col = np.array([[1,2,3,4]])

In [145]:
col

array([[1, 2, 3, 4]])

In [146]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [147]:
col.T + arr # collums by add hua raha hai 

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [148]:
arr1 = np.random.randint(1,4 ,(3,4))

In [149]:
arr1

array([[3, 2, 3, 1],
       [3, 1, 1, 3],
       [2, 1, 2, 1]], dtype=int32)

In [150]:
np.sqrt(arr1) # squarroot value nikalata hai 

array([[1.73205081, 1.41421356, 1.73205081, 1.        ],
       [1.73205081, 1.        , 1.        , 1.73205081],
       [1.41421356, 1.        , 1.41421356, 1.        ]])

In [151]:
np.exp(arr1)

array([[20.08553692,  7.3890561 , 20.08553692,  2.71828183],
       [20.08553692,  2.71828183,  2.71828183, 20.08553692],
       [ 7.3890561 ,  2.71828183,  7.3890561 ,  2.71828183]])

In [152]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.47712125, 0.        ],
       [0.47712125, 0.        , 0.        , 0.47712125],
       [0.30103   , 0.        , 0.30103   , 0.        ]])