In [1]:
#numpy - array manipulation

In [2]:
import numpy as np 

In [3]:
arr =np.random.randint(1,10,(3,4)) # resahpe tab karega arr(12 data row + collums le kar milake) me jita data hai dono se mulitple karne se otna data aana chayr reshape karne par 

In [4]:
arr

array([[4, 5, 1, 4],
       [2, 5, 5, 3],
       [4, 5, 5, 3]], dtype=int32)

In [5]:
arr.reshape(5,2) # # resahpe tab karega arr(12 data row + collums le kar milake) me jita data hai dono se mulitple karne se otna data aana chayr reshape karne par 

ValueError: cannot reshape array of size 12 into shape (5,2)

In [ ]:
arr.reshape(6,2) #6*2 = 12

In [6]:
arr.reshape(6,-5415)  # by defaulit he samjhta hai ki (-) valu hai  jo  phele value se automatic (*MULITPLE) karna shura karta hai ki  kese multiple karne se 12 atega o apne ap  value le leta hai jis * 12 yega 

array([[4, 5],
       [1, 4],
       [2, 5],
       [5, 3],
       [4, 5],
       [5, 3]], dtype=int32)

In [7]:
arr

array([[4, 5, 1, 4],
       [2, 5, 5, 3],
       [4, 5, 5, 3]], dtype=int32)

In [8]:
arr.T

array([[4, 2, 4],
       [5, 5, 5],
       [1, 5, 5],
       [4, 3, 3]], dtype=int32)

In [9]:
arr.flatten() # 1 dimension me convert kar deta hai 

array([4, 5, 1, 4, 2, 5, 5, 3, 4, 5, 5, 3], dtype=int32)

In [10]:
arr1 = np.array([1,2,3,4])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1) # axis= 1 hya  collums hai ye(expand_dims)  kiya karta hai  1D ➡ 2D bal  deta hai axis = 1 dekha deta matlab ciollums bayes dikha deta hai

array([[1],
       [2],
       [3],
       [4]])

In [13]:
np.expand_dims(arr1,axis=0) # axis= 0 hya hai row hai ye(expand_dims)  kiya karta hai  1D ➡ 2D bal  deta hai axis = 0 dekha deta matlab row bayes dikha deta hai

array([[1, 2, 3, 4]])

In [14]:
data = np.array([[1],[2],[3]])

In [15]:
data

array([[1],
       [2],
       [3]])

In [16]:
np.squeeze(data) # 2D ➡ 1D convert karta hai usko hi jisme list inter [] me ak element  hona chaye 

array([1, 2, 3])

In [17]:
arr

array([[4, 5, 1, 4],
       [2, 5, 5, 3],
       [4, 5, 5, 3]], dtype=int32)

In [18]:
np.squeeze(arr) # isme 1D me  nahi badla kyuki list ke inter [list] me ak se adhik  element  hai  

array([[4, 5, 1, 4],
       [2, 5, 5, 3],
       [4, 5, 5, 3]], dtype=int32)

In [19]:
arr1

array([1, 2, 3, 4])

In [20]:
np.repeat(arr1,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [22]:
np.roll(arr1, 2) # eder se uder kar raha hai 

array([3, 4, 1, 2])

In [24]:
np.roll(arr1, 3)

array([2, 3, 4, 1])

In [25]:
np.roll(arr1, 4)

array([1, 2, 3, 4])

In [23]:
arr1

array([1, 2, 3, 4])

In [26]:
np.diag(arr1) # 2D me convert karega value ko   diagonal rakh dega 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#numpy - binary operators

In [27]:
arr2 = np.random.randint(1,10,(3,4))

In [28]:
arr3 = np.random.randint(1,10,(3,4))

In [29]:
arr2

array([[7, 5, 8, 6],
       [9, 8, 9, 6],
       [2, 5, 4, 4]], dtype=int32)

In [30]:
arr3

array([[7, 4, 7, 2],
       [8, 8, 8, 2],
       [4, 3, 7, 5]], dtype=int32)

In [31]:
 arr2 + arr3

array([[14,  9, 15,  8],
       [17, 16, 17,  8],
       [ 6,  8, 11,  9]], dtype=int32)

In [32]:
arr2 - arr3

array([[ 0,  1,  1,  4],
       [ 1,  0,  1,  4],
       [-2,  2, -3, -1]], dtype=int32)

In [33]:
arr2/arr3

array([[1.        , 1.25      , 1.14285714, 3.        ],
       [1.125     , 1.        , 1.125     , 3.        ],
       [0.5       , 1.66666667, 0.57142857, 0.8       ]])

In [34]:
arr2*arr3

array([[49, 20, 56, 12],
       [72, 64, 72, 12],
       [ 8, 15, 28, 20]], dtype=int32)

In [35]:
arr2%arr3 # % remder operation hai jisme jo bachega o aa jaye ga ex- 7/7 = 0 kuch nani bacha 5/4 = 1 ak batch that is remeder value 

array([[0, 1, 1, 0],
       [1, 0, 1, 0],
       [2, 2, 4, 4]], dtype=int32)

In [36]:
arr2**arr3

array([[  823543,      625,  2097152,       36],
       [43046721, 16777216, 43046721,       36],
       [      16,      125,    16384,     1024]], dtype=int32)

In [37]:
7**7

823543

In [38]:
5**4

625

In [39]:
arr2 & arr3 # & - and hota hai  binary-type data zyada useful hota hai. binary me  ager data mill raha dono data likhe do ager nahi mill raha chota data liya jata ahi 

array([[7, 4, 0, 2],
       [8, 8, 8, 2],
       [0, 1, 4, 4]], dtype=int32)

In [41]:
arr2

array([[7, 5, 8, 6],
       [9, 8, 9, 6],
       [2, 5, 4, 4]], dtype=int32)

In [42]:
arr3 

array([[7, 4, 7, 2],
       [8, 8, 8, 2],
       [4, 3, 7, 5]], dtype=int32)

In [44]:
arr2|arr3 ## & - and hota hai  binary-type data zyada useful hota hai. binary me  ager data mill raha dono data likhe do ager nahi mill raha bada  data liya jata ahi 

array([[ 7,  5, 15,  6],
       [ 9,  8,  9,  6],
       [ 6,  7,  7,  5]], dtype=int32)

In [43]:
~arr2

array([[ -8,  -6,  -9,  -7],
       [-10,  -9, -10,  -7],
       [ -3,  -6,  -5,  -5]], dtype=int32)

In [45]:
arr2 > arr3

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [False,  True, False, False]])

In [46]:
#numpy = string functions

In [48]:
arr4 = np.array(['sajan','sanjay'])

In [49]:
arr4

array(['sajan', 'sanjay'], dtype='<U6')

In [51]:
np.char.upper(arr4)

array(['SAJAN', 'SANJAY'], dtype='<U6')

In [53]:
np.char.title(arr4) # title matlab first letter uppercase  baaki sab letters lowercase kar deta hai

array(['Sajan', 'Sanjay'], dtype='<U6')

In [54]:
np.char.capitalize(arr4) #first letter uppercase bana deta hai baaki sab letters lowercase kar deta hai

array(['Sajan', 'Sanjay'], dtype='<U6')

In [55]:
arr5 = np.array(["sAjAn", "KUmar", "data SCIENCE"])

In [56]:
arr5

array(['sAjAn', 'KUmar', 'data SCIENCE'], dtype='<U12')

In [57]:
np.char.title(arr5)

array(['Sajan', 'Kumar', 'Data Science'], dtype='<U12')

In [58]:
np.char.capitalize(arr5) #np.char.title(arr5) same to same 

array(['Sajan', 'Kumar', 'Data science'], dtype='<U12')

In [60]:
#numpy - mathematical functions

In [62]:
arr

array([[4, 5, 1, 4],
       [2, 5, 5, 3],
       [4, 5, 5, 3]], dtype=int32)

In [65]:
np.sin(arr)

array([[-0.7568025 , -0.95892427,  0.84147098, -0.7568025 ],
       [ 0.90929743, -0.95892427, -0.95892427,  0.14112001],
       [-0.7568025 , -0.95892427, -0.95892427,  0.14112001]])

In [64]:
np.cos(arr)

array([[-0.65364362,  0.28366219,  0.54030231, -0.65364362],
       [-0.41614684,  0.28366219,  0.28366219, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.28366219, -0.9899925 ]])

In [66]:
np.tan(arr)

array([[ 1.15782128, -3.38051501,  1.55740772,  1.15782128],
       [-2.18503986, -3.38051501, -3.38051501, -0.14254654],
       [ 1.15782128, -3.38051501, -3.38051501, -0.14254654]])

In [67]:
np.tanh(arr)

array([[0.9993293 , 0.9999092 , 0.76159416, 0.9993293 ],
       [0.96402758, 0.9999092 , 0.9999092 , 0.99505475],
       [0.9993293 , 0.9999092 , 0.9999092 , 0.99505475]])

In [68]:
np.log10(arr)

array([[0.60205999, 0.69897   , 0.        , 0.60205999],
       [0.30103   , 0.69897   , 0.69897   , 0.47712125],
       [0.60205999, 0.69897   , 0.69897   , 0.47712125]])

In [69]:
np.exp(arr)

array([[ 54.59815003, 148.4131591 ,   2.71828183,  54.59815003],
       [  7.3890561 , 148.4131591 , 148.4131591 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 148.4131591 ,  20.08553692]])

In [73]:
arr

array([[4, 5, 1, 4],
       [2, 5, 5, 3],
       [4, 5, 5, 3]], dtype=int32)

In [70]:
np.sqrt(arr)

array([[2.        , 2.23606798, 1.        , 2.        ],
       [1.41421356, 2.23606798, 2.23606798, 1.73205081],
       [2.        , 2.23606798, 2.23606798, 1.73205081]])

In [76]:
np.power(arr,2) #**2

array([[16, 25,  1, 16],
       [ 4, 25, 25,  9],
       [16, 25, 25,  9]], dtype=int32)

In [77]:
np.mean(arr)

np.float64(3.8333333333333335)

In [78]:
np.median(arr)

np.float64(4.0)

In [79]:
np.std(arr)

np.float64(1.2801909579781015)

In [81]:
np.var(arr)

np.float64(1.6388888888888893)

In [82]:
np.max(arr)

np.int32(5)

In [83]:
np.min(arr)

np.int32(1)