In [1]:
#sort,sarch & counting functions

In [3]:
import numpy as np

In [4]:
arr = np.array([4,3,4,6,72,3,455,6,6,9])

In [13]:
sort_arr = np.sort(arr)

In [14]:
sort_arr

array([  3,   3,   4,   4,   6,   6,   6,   9,  72, 455])

In [17]:
np.searchsorted(sort_arr,5) # batata hai ki 5 ko kis index par insert kiya jaye taaki array sorted rahe.

np.int64(4)

In [18]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [19]:
np.count_nonzero(arr1)

np.int64(2)

In [20]:
arr

array([  4,   3,   4,   6,  72,   3, 455,   6,   6,   9])

In [21]:
np.where(arr > 6) # index bata hia kese index bada hai

(array([4, 6, 9]),)

In [22]:
np.extract(arr > 6 , arr)

array([ 72, 455,   9])

In [24]:
np.extract(arr > 4 , arr)

array([  6,  72, 455,   6,   6,   9])

In [25]:
np.extract(arr >= 4 , arr)

array([  4,   4,   6,  72, 455,   6,   6,   9])

In [26]:
#numpy - byte swapping

In [27]:
arr

array([  4,   3,   4,   6,  72,   3, 455,   6,   6,   9])

In [28]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         432345564227567616,  5188146770730811392,   216172782113783808,
       -4107001385185181696,   432345564227567616,   432345564227567616,
         648518346341351424])

In [29]:
#numpy - copies & view

In [30]:
arr

array([  4,   3,   4,   6,  72,   3, 455,   6,   6,   9])

In [31]:
a = np.copy(arr)

In [32]:
b = arr.view() # like b = arr like this b me change aruga arr me bh ho jayeg same to same arr change b bhi change hoga  

In [34]:
b

array([  4,   3,   4,   6,  72,   3, 455,   6,   6,   9])

In [35]:
arr

array([  4,   3,   4,   6,  72,   3, 455,   6,   6,   9])

In [36]:
b[0]=100

In [37]:
b

array([100,   3,   4,   6,  72,   3, 455,   6,   6,   9])

In [38]:
arr

array([100,   3,   4,   6,  72,   3, 455,   6,   6,   9])

In [39]:
arr[1]=200

In [40]:
arr

array([100, 200,   4,   6,  72,   3, 455,   6,   6,   9])

In [41]:
b

array([100, 200,   4,   6,  72,   3, 455,   6,   6,   9])

In [42]:
#numpy - matrix library

In [44]:
import numpy.matlib as nm

In [45]:
nm.zeros(5) #array genret kar raha tha matrix genret kare min 2D hoga important note array superclass hai matrix sub class hai matlab array ke ander matrix ata hai

matrix([[0., 0., 0., 0., 0.]])

In [49]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [50]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [51]:
nm.random.randint(1,10,(3,4))

array([[7, 7, 4, 6],
       [9, 8, 7, 2],
       [7, 6, 7, 4]], dtype=int32)

In [ ]:
# NOTE -- numpy.matlib library o same to same numpy library me hai jo hum numpy me kar rehe the o sab hum  numpy.matlib  kar sate hai 

In [52]:
#numpy - linear algebra

In [66]:
arr2 = np.random.randint(0,4,(2,2))

In [67]:
arr3 = np.random.randint(0,3,(2,2))

In [68]:
arr2

array([[3, 1],
       [2, 0]], dtype=int32)

In [69]:
arr3

array([[1, 1],
       [2, 2]], dtype=int32)

In [70]:
np.dot(arr2,arr3) # matrix byes multipication ho raha same to  same arr2@arr3 ye hai

array([[5, 5],
       [2, 2]], dtype=int32)

In [71]:
arr2@arr3 # @ matrix byes multipication chiha

array([[5, 5],
       [2, 2]], dtype=int32)